site_name: "Datastorm"

site_author: "Javier Luna Molina"

# MkDocs pages configuration. The `<<` operator is sugar added by pydocmd
# that allows you to use an external Markdown file (eg. your project's README)
# in the documentation. The path must be relative to current working directory.
nav:
- Home: ../README.md


# These options all show off their default values. You don't have to add
# them to your configuration if you're fine with the default.
docs_dir: docs/_build
theme:    readthedocs

repo_url: https://github.com/JavierLuna/datastorm/
